# Site settings
title: Naja Nicole Gordon
header-img: img/home-bg.jpg
description: "Landing Page of Naja Nicole Gordon"
baseurl: ""


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
